#!/bin/sh

RLWRAP=`which rlwrap`

DIR=`dirname $0`

# You'll never see messages echoed here unless something fails,
# because Shuffletron currently clears the screen at startup. Oops.

if [ -r $DIR/libs/libmixalot-mpg123.so.0 ] ; then
    echo "Using local shared library directory."
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./libs/:/usr/local/lib/shuffletron
else
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/shuffletron
fi

if [ -z $RLWRAP ] ; then
   echo "** Can't find rlwrap. It's recommended you install this, in order to"
   echo "   have full command editing and history."
   $0-bin
else
   rlwrap $0-bin $@
fi
