#!/bin/sh

RLWRAP=`which rlwrap`

if [ -r `dirname $0`/libs/libmixalot-mpg123.so.0 ] ; then
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./libs/
else
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/shuffletron
fi

if [ -z $RLWRAP ] ; then
   echo "** Can't find rlwrap. It's recommended you install this, in order to"
   echo "   have full command editing and history."
   $0-bin
else
   rlwrap $0-bin
fi
